# Generated by Django 4.2.6 on 2023-10-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(upload_to='slider_img/')),
                ('slider_title', models.CharField(max_length=200, verbose_name='Title')),
                ('slider_text', models.CharField(max_length=200, verbose_name='Text')),
                ('slider_css', models.CharField(default='-', max_length=200, null=True, verbose_name='CSS class')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
    ]
