# Generated by Django 4.2.6 on 2023-10-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidercontent',
            name='slider_img',
            field=models.ImageField(upload_to='slider_img/', verbose_name='Image'),
        ),
    ]
